// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internalrpc/internalrpc.proto

package internalrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Exact JSON body the HTTP twin accepts (OpenRTB BidRequest).
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// Forwarded control headers (e.g. X-Dev-Slow-DSPs). Trace context rides
	// gRPC metadata via the otel propagator, never here.
	Headers       map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAuctionRequest) Reset() {
	*x = RunAuctionRequest{}
	mi := &file_internalrpc_internalrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAuctionRequest) ProtoMessage() {}

func (x *RunAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internalrpc_internalrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAuctionRequest.ProtoReflect.Descriptor instead.
func (*RunAuctionRequest) Descriptor() ([]byte, []int) {
	return file_internalrpc_internalrpc_proto_rawDescGZIP(), []int{0}
}

func (x *RunAuctionRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RunAuctionRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RunAuctionRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type RunAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Exact JSON body the HTTP twin returns (OpenRTB BidResponse).
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// HTTP-equivalent status code from the bridged handler.
	Status        int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAuctionResponse) Reset() {
	*x = RunAuctionResponse{}
	mi := &file_internalrpc_internalrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAuctionResponse) ProtoMessage() {}

func (x *RunAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internalrpc_internalrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAuctionResponse.ProtoReflect.Descriptor instead.
func (*RunAuctionResponse) Descriptor() ([]byte, []int) {
	return file_internalrpc_internalrpc_proto_rawDescGZIP(), []int{1}
}

func (x *RunAuctionResponse) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RunAuctionResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RunAuctionResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Exact JSON body the HTTP twin accepts (OpenRTB BidRequest).
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// Forwarded control headers (e.g. X-Dev-Delay-Ms).
	Headers       map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_internalrpc_internalrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internalrpc_internalrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_internalrpc_internalrpc_proto_rawDescGZIP(), []int{2}
}

func (x *BidRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *BidRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *BidRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Exact JSON body the HTTP twin returns (OpenRTB BidResponse).
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// HTTP-equivalent status code from the bridged handler.
	Status        int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_internalrpc_internalrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internalrpc_internalrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_internalrpc_internalrpc_proto_rawDescGZIP(), []int{3}
}

func (x *BidResponse) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *BidResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *BidResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ServeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Exact JSON body the HTTP twin accepts (models.ServeRequest).
	Body          []byte            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeRequest) Reset() {
	*x = ServeRequest{}
	mi := &file_internalrpc_internalrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeRequest) ProtoMessage() {}

func (x *ServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internalrpc_internalrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeRequest.ProtoReflect.Descriptor instead.
func (*ServeRequest) Descriptor() ([]byte, []int) {
	return file_internalrpc_internalrpc_proto_rawDescGZIP(), []int{4}
}

func (x *ServeRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ServeRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServeRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ServeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Exact JSON body the HTTP twin returns (models.ServeResponse).
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// HTTP-equivalent status; 429 = frequency-cap decline (normal no-fill).
	Status        int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeResponse) Reset() {
	*x = ServeResponse{}
	mi := &file_internalrpc_internalrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeResponse) ProtoMessage() {}

func (x *ServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internalrpc_internalrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeResponse.ProtoReflect.Descriptor instead.
func (*ServeResponse) Descriptor() ([]byte, []int) {
	return file_internalrpc_internalrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ServeResponse) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ServeResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServeResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_internalrpc_internalrpc_proto protoreflect.FileDescriptor

const file_internalrpc_internalrpc_proto_rawDesc = "" +
	"\n" +
	"\x1dinternalrpc/internalrpc.proto\x12\x12adtech.internalrpc\"\xd8\x01\n" +
	"\x11RunAuctionRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12L\n" +
	"\aheaders\x18\x03 \x03(\v22.adtech.internalrpc.RunAuctionRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x12RunAuctionResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xca\x01\n" +
	"\n" +
	"BidRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12E\n" +
	"\aheaders\x18\x03 \x03(\v2+.adtech.internalrpc.BidRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\vBidResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xce\x01\n" +
	"\fServeRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12G\n" +
	"\aheaders\x18\x03 \x03(\v2-.adtech.internalrpc.ServeRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\rServeResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status2u\n" +
	"\x16InternalAuctionService\x12[\n" +
	"\n" +
	"RunAuction\x12%.adtech.internalrpc.RunAuctionRequest\x1a&.adtech.internalrpc.RunAuctionResponse2\\\n" +
	"\x12InternalBidService\x12F\n" +
	"\x03Bid\x12\x1e.adtech.internalrpc.BidRequest\x1a\x1f.adtech.internalrpc.BidResponse2f\n" +
	"\x16InternalAdServeService\x12L\n" +
	"\x05Serve\x12 .adtech.internalrpc.ServeRequest\x1a!.adtech.internalrpc.ServeResponseBBZ@github.com/MichaelJohnWatters/ad-tech-mono/pkg/proto/internalrpcb\x06proto3"

var (
	file_internalrpc_internalrpc_proto_rawDescOnce sync.Once
	file_internalrpc_internalrpc_proto_rawDescData []byte
)

func file_internalrpc_internalrpc_proto_rawDescGZIP() []byte {
	file_internalrpc_internalrpc_proto_rawDescOnce.Do(func() {
		file_internalrpc_internalrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internalrpc_internalrpc_proto_rawDesc), len(file_internalrpc_internalrpc_proto_rawDesc)))
	})
	return file_internalrpc_internalrpc_proto_rawDescData
}

var file_internalrpc_internalrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internalrpc_internalrpc_proto_goTypes = []any{
	(*RunAuctionRequest)(nil),  // 0: adtech.internalrpc.RunAuctionRequest
	(*RunAuctionResponse)(nil), // 1: adtech.internalrpc.RunAuctionResponse
	(*BidRequest)(nil),         // 2: adtech.internalrpc.BidRequest
	(*BidResponse)(nil),        // 3: adtech.internalrpc.BidResponse
	(*ServeRequest)(nil),       // 4: adtech.internalrpc.ServeRequest
	(*ServeResponse)(nil),      // 5: adtech.internalrpc.ServeResponse
	nil,                        // 6: adtech.internalrpc.RunAuctionRequest.HeadersEntry
	nil,                        // 7: adtech.internalrpc.BidRequest.HeadersEntry
	nil,                        // 8: adtech.internalrpc.ServeRequest.HeadersEntry
}
var file_internalrpc_internalrpc_proto_depIdxs = []int32{
	6, // 0: adtech.internalrpc.RunAuctionRequest.headers:type_name -> adtech.internalrpc.RunAuctionRequest.HeadersEntry
	7, // 1: adtech.internalrpc.BidRequest.headers:type_name -> adtech.internalrpc.BidRequest.HeadersEntry
	8, // 2: adtech.internalrpc.ServeRequest.headers:type_name -> adtech.internalrpc.ServeRequest.HeadersEntry
	0, // 3: adtech.internalrpc.InternalAuctionService.RunAuction:input_type -> adtech.internalrpc.RunAuctionRequest
	2, // 4: adtech.internalrpc.InternalBidService.Bid:input_type -> adtech.internalrpc.BidRequest
	4, // 5: adtech.internalrpc.InternalAdServeService.Serve:input_type -> adtech.internalrpc.ServeRequest
	1, // 6: adtech.internalrpc.InternalAuctionService.RunAuction:output_type -> adtech.internalrpc.RunAuctionResponse
	3, // 7: adtech.internalrpc.InternalBidService.Bid:output_type -> adtech.internalrpc.BidResponse
	5, // 8: adtech.internalrpc.InternalAdServeService.Serve:output_type -> adtech.internalrpc.ServeResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internalrpc_internalrpc_proto_init() }
func file_internalrpc_internalrpc_proto_init() {
	if File_internalrpc_internalrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internalrpc_internalrpc_proto_rawDesc), len(file_internalrpc_internalrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internalrpc_internalrpc_proto_goTypes,
		DependencyIndexes: file_internalrpc_internalrpc_proto_depIdxs,
		MessageInfos:      file_internalrpc_internalrpc_proto_msgTypes,
	}.Build()
	File_internalrpc_internalrpc_proto = out.File
	file_internalrpc_internalrpc_proto_goTypes = nil
	file_internalrpc_internalrpc_proto_depIdxs = nil
}
