// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: internalrpc/internalrpc.proto

package internalrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalAuctionService_RunAuction_FullMethodName = "/adtech.internalrpc.InternalAuctionService/RunAuction"
)

// InternalAuctionServiceClient is the client API for InternalAuctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalAuctionService is the gRPC twin of POST /v1/openrtb/auction (exchange).
type InternalAuctionServiceClient interface {
	RunAuction(ctx context.Context, in *RunAuctionRequest, opts ...grpc.CallOption) (*RunAuctionResponse, error)
}

type internalAuctionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalAuctionServiceClient(cc grpc.ClientConnInterface) InternalAuctionServiceClient {
	return &internalAuctionServiceClient{cc}
}

func (c *internalAuctionServiceClient) RunAuction(ctx context.Context, in *RunAuctionRequest, opts ...grpc.CallOption) (*RunAuctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunAuctionResponse)
	err := c.cc.Invoke(ctx, InternalAuctionService_RunAuction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalAuctionServiceServer is the server API for InternalAuctionService service.
// All implementations must embed UnimplementedInternalAuctionServiceServer
// for forward compatibility.
//
// InternalAuctionService is the gRPC twin of POST /v1/openrtb/auction (exchange).
type InternalAuctionServiceServer interface {
	RunAuction(context.Context, *RunAuctionRequest) (*RunAuctionResponse, error)
	mustEmbedUnimplementedInternalAuctionServiceServer()
}

// UnimplementedInternalAuctionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalAuctionServiceServer struct{}

func (UnimplementedInternalAuctionServiceServer) RunAuction(context.Context, *RunAuctionRequest) (*RunAuctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAuction not implemented")
}
func (UnimplementedInternalAuctionServiceServer) mustEmbedUnimplementedInternalAuctionServiceServer() {
}
func (UnimplementedInternalAuctionServiceServer) testEmbeddedByValue() {}

// UnsafeInternalAuctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalAuctionServiceServer will
// result in compilation errors.
type UnsafeInternalAuctionServiceServer interface {
	mustEmbedUnimplementedInternalAuctionServiceServer()
}

func RegisterInternalAuctionServiceServer(s grpc.ServiceRegistrar, srv InternalAuctionServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalAuctionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalAuctionService_ServiceDesc, srv)
}

func _InternalAuctionService_RunAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAuctionServiceServer).RunAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAuctionService_RunAuction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAuctionServiceServer).RunAuction(ctx, req.(*RunAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalAuctionService_ServiceDesc is the grpc.ServiceDesc for InternalAuctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalAuctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adtech.internalrpc.InternalAuctionService",
	HandlerType: (*InternalAuctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunAuction",
			Handler:    _InternalAuctionService_RunAuction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalrpc/internalrpc.proto",
}

const (
	InternalBidService_Bid_FullMethodName = "/adtech.internalrpc.InternalBidService/Bid"
)

// InternalBidServiceClient is the client API for InternalBidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalBidService is the gRPC twin of POST /v1/openrtb/bid (our DSP only —
// third-party DSPs are always called over OpenRTB HTTP).
type InternalBidServiceClient interface {
	Bid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponse, error)
}

type internalBidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalBidServiceClient(cc grpc.ClientConnInterface) InternalBidServiceClient {
	return &internalBidServiceClient{cc}
}

func (c *internalBidServiceClient) Bid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidResponse)
	err := c.cc.Invoke(ctx, InternalBidService_Bid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalBidServiceServer is the server API for InternalBidService service.
// All implementations must embed UnimplementedInternalBidServiceServer
// for forward compatibility.
//
// InternalBidService is the gRPC twin of POST /v1/openrtb/bid (our DSP only —
// third-party DSPs are always called over OpenRTB HTTP).
type InternalBidServiceServer interface {
	Bid(context.Context, *BidRequest) (*BidResponse, error)
	mustEmbedUnimplementedInternalBidServiceServer()
}

// UnimplementedInternalBidServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalBidServiceServer struct{}

func (UnimplementedInternalBidServiceServer) Bid(context.Context, *BidRequest) (*BidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedInternalBidServiceServer) mustEmbedUnimplementedInternalBidServiceServer() {}
func (UnimplementedInternalBidServiceServer) testEmbeddedByValue()                            {}

// UnsafeInternalBidServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalBidServiceServer will
// result in compilation errors.
type UnsafeInternalBidServiceServer interface {
	mustEmbedUnimplementedInternalBidServiceServer()
}

func RegisterInternalBidServiceServer(s grpc.ServiceRegistrar, srv InternalBidServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalBidServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalBidService_ServiceDesc, srv)
}

func _InternalBidService_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalBidServiceServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalBidService_Bid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalBidServiceServer).Bid(ctx, req.(*BidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalBidService_ServiceDesc is the grpc.ServiceDesc for InternalBidService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalBidService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adtech.internalrpc.InternalBidService",
	HandlerType: (*InternalBidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bid",
			Handler:    _InternalBidService_Bid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalrpc/internalrpc.proto",
}

const (
	InternalAdServeService_Serve_FullMethodName = "/adtech.internalrpc.InternalAdServeService/Serve"
)

// InternalAdServeServiceClient is the client API for InternalAdServeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalAdServeService is the gRPC twin of POST /v1/ad/serve (ad server).
type InternalAdServeServiceClient interface {
	Serve(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeResponse, error)
}

type internalAdServeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalAdServeServiceClient(cc grpc.ClientConnInterface) InternalAdServeServiceClient {
	return &internalAdServeServiceClient{cc}
}

func (c *internalAdServeServiceClient) Serve(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServeResponse)
	err := c.cc.Invoke(ctx, InternalAdServeService_Serve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalAdServeServiceServer is the server API for InternalAdServeService service.
// All implementations must embed UnimplementedInternalAdServeServiceServer
// for forward compatibility.
//
// InternalAdServeService is the gRPC twin of POST /v1/ad/serve (ad server).
type InternalAdServeServiceServer interface {
	Serve(context.Context, *ServeRequest) (*ServeResponse, error)
	mustEmbedUnimplementedInternalAdServeServiceServer()
}

// UnimplementedInternalAdServeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalAdServeServiceServer struct{}

func (UnimplementedInternalAdServeServiceServer) Serve(context.Context, *ServeRequest) (*ServeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Serve not implemented")
}
func (UnimplementedInternalAdServeServiceServer) mustEmbedUnimplementedInternalAdServeServiceServer() {
}
func (UnimplementedInternalAdServeServiceServer) testEmbeddedByValue() {}

// UnsafeInternalAdServeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalAdServeServiceServer will
// result in compilation errors.
type UnsafeInternalAdServeServiceServer interface {
	mustEmbedUnimplementedInternalAdServeServiceServer()
}

func RegisterInternalAdServeServiceServer(s grpc.ServiceRegistrar, srv InternalAdServeServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalAdServeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalAdServeService_ServiceDesc, srv)
}

func _InternalAdServeService_Serve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalAdServeServiceServer).Serve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalAdServeService_Serve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalAdServeServiceServer).Serve(ctx, req.(*ServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalAdServeService_ServiceDesc is the grpc.ServiceDesc for InternalAdServeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalAdServeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adtech.internalrpc.InternalAdServeService",
	HandlerType: (*InternalAdServeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Serve",
			Handler:    _InternalAdServeService_Serve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalrpc/internalrpc.proto",
}
