-- +goose Up
-- Data-monetization receivables (ADR 0009 phase 2): external seats hold no
-- prepay balance, so their accrued data fees (ledger account
-- extseat:{seat}:payable) are invoiced out-of-band. One row per
-- (winner_seat, period): the total the buyer owes, with a per-owner/segment
-- breakdown for the operator. Generated by invoice-runner alongside the
-- monthly advertiser invoices; idempotent per the UNIQUE key (re-runs
-- replace totals + breakdown).
--
-- Operator-facing service table (winner_seat is not a tenant): no
-- account_id, no RLS — same precedent as batch_runs / config_schema.
CREATE TABLE data_fee_receivables (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    winner_seat  TEXT NOT NULL,
    period_start DATE NOT NULL,
    period_end   DATE NOT NULL, -- exclusive
    impressions  BIGINT NOT NULL,
    total_micros BIGINT NOT NULL,
    -- breakdown: [{owner_account_id, segment_id, impressions, fee_micros}]
    breakdown    JSONB NOT NULL DEFAULT '[]',
    status       TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'paid', 'void')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (winner_seat, period_start, period_end)
);

-- +goose Down
DROP TABLE data_fee_receivables;
