apiVersion: v1
kind: Service
metadata:
  name: pipeline
  namespace: adtech
  labels:
    app: pipeline
spec:
  selector:
    app: pipeline
  ports:
    - name: http
      port: 8087
      targetPort: 8087
