apiVersion: v1
kind: Service
metadata:
  name: webhooks
  namespace: adtech
  labels:
    app: webhooks
spec:
  selector:
    app: webhooks
  ports:
    - name: http
      port: 8091
      targetPort: 8091
