package main

import (
	"github.com/MichaelJohnWatters/ad-tech-mono/pkg/config"
	"github.com/MichaelJohnWatters/ad-tech-mono/pkg/constants"
)

// reportingSchema is the reporting service's owned config keys. Passed to
// config.Setup at boot; the pod writes the full schema (these + platform
// defaults) into its service_registry row.
var reportingSchema = []config.SchemaEntry{
	{Key: "reporting.nats_url", Type: "string", Tier: config.TierStatic, Default: "nats://localhost:4222", Description: "NATS JetStream URL the reporting service consumes events from.", Service: constants.ServiceReporting, Since: "v1.0"},
	{Key: "reporting.rollup_enabled", Type: "bool", Tier: config.TierLive, Default: "false", Description: "Run scheduled rollups (minute/hour/day/month aggregates) inside this pod. Off in dev; on in prod where rollup ownership is centralised here.", Service: constants.ServiceReporting, Since: "v1.0"},
	{Key: "reporting.billing_enabled", Type: "bool", Tier: config.TierLive, Default: "true", Description: "Accrue billable spend in the billing ledger as AuctionWinEvents arrive. Disable to silence billing side-effects during replays.", Service: constants.ServiceReporting, Since: "v1.0"},
	{Key: "cache.warm.billing_rates.poll_interval", Type: "duration", Tier: config.TierStatic, Default: "300s", Description: "How often the publisher billing-rate cache refreshes. Long interval is fine — rates rarely change and a stale rate just delays the new revshare by a few minutes.", Service: constants.ServiceReporting, Since: "v1.1"},
	{Key: "billing.ledger_backend", Type: "string", Tier: config.TierStatic, Default: "memory", Description: "Backing store for the billing ledger: 'memory' (in-process slice, volatile) or 'tigerbeetle' (durable TB cluster). Memory is fine for dev/CI; tigerbeetle is the prod story.", Service: constants.ServiceReporting, Since: "v1.2"},
	{Key: "reporting.analytics_backend", Type: "string", Tier: config.TierStatic, Default: "memory", Description: "Backing store for analytics events: 'memory' (in-process, volatile — events lost on restart), 'duckdb' (embedded columnar file; needs `-tags duckdb CGO_ENABLED=1`), or 'clickhouse' (server, pure-Go client, no CGO). Memory is the unit-test/CI default; clickhouse is the full-local + prod event store (see docs/adr/0001-analytics-engines.md); duckdb is the embedded local option.", Service: constants.ServiceReporting, Since: "v1.3"},
	{Key: "reporting.clickhouse_addr", Type: "string", Tier: config.TierStatic, Default: "127.0.0.1:9000", Description: "Comma-separated ClickHouse native-protocol addresses (host:port). Only consulted when reporting.analytics_backend=clickhouse. Locally the Tiltfile port-forwards 9000 to the in-cluster clickhouse service.", Service: constants.ServiceReporting, Since: "v1.4"},
	{Key: "reporting.clickhouse_database", Type: "string", Tier: config.TierStatic, Default: "adtech", Description: "ClickHouse database name. Only consulted when reporting.analytics_backend=clickhouse.", Service: constants.ServiceReporting, Since: "v1.4"},
	{Key: "reporting.clickhouse_user", Type: "string", Tier: config.TierStatic, Default: "adtech", Description: "ClickHouse username. Only consulted when reporting.analytics_backend=clickhouse.", Service: constants.ServiceReporting, Since: "v1.4"},
	{Key: "reporting.clickhouse_password", Type: "string", Tier: config.TierSecret, Default: "adtech-local-dev", Description: "ClickHouse password. Only consulted when reporting.analytics_backend=clickhouse. Prod overlays should source this from a K8s Secret.", Service: constants.ServiceReporting, Since: "v1.4"},
	{Key: "reporting.duckdb_path", Type: "string", Tier: config.TierStatic, Default: "/tmp/adtech-analytics.duckdb", Description: "Filesystem path for the DuckDB analytics file. Only consulted when reporting.analytics_backend=duckdb. In prod this should point at a PersistentVolumeClaim mount so the file survives pod rescheduling.", Service: constants.ServiceReporting, Since: "v1.3"},
	{Key: "reporting.clickhouse_batch_consumer", Type: "bool", Tier: config.TierStatic, Default: "false", Description: "Consume the high-volume core events (impression/click/conversion/view/auction/win/media) in bulk — one atomic ClickHouse block insert per JetStream fetch instead of one INSERT per event (avoids the 'too many parts' anti-pattern). Requires a backend with bulk-insert support (clickhouse); no-op on memory/duckdb. Per-message dedup (Redis SetNX on stream sequence) makes redelivery idempotent.", Service: constants.ServiceReporting, Since: "v1.5"},
	{Key: "reporting.dedup_ttl", Type: "duration", Tier: config.TierStatic, Default: "24h", Description: "How long a processed message's dedup marker is retained (Redis SetNX). Bounds the redelivery window the batch consumer dedups against; should exceed the JetStream stream MaxAge. Only consulted when reporting.clickhouse_batch_consumer=true.", Service: constants.ServiceReporting, Since: "v1.5"},
	{Key: "billing.tigerbeetle_addresses", Type: "string", Tier: config.TierStatic, Default: "127.0.0.1:3033", Description: "Comma-separated TigerBeetle replica addresses (host:port). Only consulted when billing.ledger_backend=tigerbeetle. Locally the Tiltfile port-forwards 3033 → in-cluster 3000.", Service: constants.ServiceReporting, Since: "v1.2"},
	{Key: "reporting.spend_snapshot_enabled", Type: "bool", Tier: config.TierLive, Default: "true", Description: "Periodically broadcast per-campaign committed spend (settled + open reserves) on adtech.billing.campaign_spend_snapshot so DSPs reconcile pacing to billed reality. Disable to fall back to the DSP's local win-notice decrement only.", Service: constants.ServiceReporting, Since: "v1.6"},
	{Key: "reporting.spend_snapshot_interval", Type: "duration", Tier: config.TierLive, Default: "30s", Description: "How often the committed-spend snapshot is published. Shorter = DSP pacing tracks billed spend more tightly (smaller intra-snapshot over-count window) at the cost of more NATS traffic.", Service: constants.ServiceReporting, Since: "v1.6"},
	{Key: "reporting.pacing_hold_ttl", Type: "duration", Tier: config.TierLive, Default: "15m", Description: "How long an open reserve (impression awaiting its click/conversion/view settle) counts toward a campaign's committed spend before it's swept and released. A reserve that never settles is an impression whose billable event never arrived — freeing it stops it pacing the campaign forever.", Service: constants.ServiceReporting, Since: "v1.6"},
}
