apiVersion: v1
kind: Service
metadata:
  name: identity-consumer
  namespace: adtech
  labels:
    app: identity-consumer
spec:
  selector:
    app: identity-consumer
  ports:
    - name: http
      port: 8092
      targetPort: 8092
